### ISSUE TITLE
Homebridge's configuration service?

### ISSUE THREAD

**Issue by robertvorthman** [KhaosT/homebridge-amazondash#1]
Step #3 of your readme says "...or use Homebridge's configuration service on iOS".  Could you please clarify?  Is there some way of updating Homebridge's config.json by using iOS instead of manually editing the json?  Thanks

**Comment by KhaosT** [comment]
@robertvorthman yeah, in homebridge 0.3 introduces plugin 2.0 model which allows homebridge to cache and config plugin from using a specific protocol. Here is [a sample app](https://github.com/KhaosT/HesperusBridgeConfigurator) that adopts this protocol, or you can download [Hesperus](https://itunes.apple.com/us/app/hesperus/id969348892?ls=1&mt=8) and use that to config the plugin.

**Comment by robertvorthman** [comment]
Thanks
