### ISSUE TITLE
Dash button not showing up as supported in iOS 10 Home

### ISSUE THREAD

**Issue by pewtertankard** [KhaosT/homebridge-amazondash#10]
Hi there. I've configured homebridge-amazondash as you suggested, put the correct MAC address into the config.json file.

Am running this on a FreeBSD jail by the way, hence slight differences. However, running bin/findbutton as per instructions shows button presses OK.

Homebridge, on loading merely says "Initializing AmazonDash platform..." but then doesn't say what it's looking for (and I never see anything in the log when I do press the button).

The accessory shows up in iOS 10 Home but it says "Not supported". It's obviously in the configuration but I don't know if it's being reported correctly.  Any suggestions you can offer would be welcomed. Thanks.

***UPDATE*** : This does work if I use a configuration app like Home from selfcoded.com as "Triggers". However, I can't then amend those same "Automations" in iOS 10's native Home app as the Dash button isn't a supported accessory.

**Comment by kolossboss** [comment]
U can use apps like Hesperus so set up the Dash Button

**Comment by pewtertankard** [comment]
As you'll see from my update, yes I've done this but the button is still showing up as not supported in iOS 10 Home and I need to be careful not to touch anything now under iOS 10 Home "Automations" to avoid screwing up the triggers I set up using third party tools. My issue is still open as I don't know if this is expected behaviour and, if so, shouldn't it be listed in the README to avoid future confusion. Thanks

**Comment by 1inuxoid** [comment]
I have the same issue in iOS 10 Home application as @pewtertankard - buttons appear on the app, but are shown as unsupported and can't be used for Automations.
I also have these messages from node_pcap coming quite often in homebridge logs:
"node_pcap: EthernetFrame() - Don't know how to decode ethertype 34969"

**Comment by 1inuxoid** [comment]
I wonder if buttons are implemented as accessories, why do I have this message during startup:
`Dec 08 21:53:35 homenas homebridge[22004]: [12/8/2016, 9:53:35 PM] Initializing AmazonDash platform...
Dec 08 21:53:35 homenas homebridge[22004]: [12/8/2016, 9:53:35 PM] Loading 0 accessories...`

And I double checked mac addresses in config.json. How can I help in looking into it?

**Comment by KhaosT** [comment]
As of iOS 10.2, Apple's Home app still don't support programable switch. Please use third party HomeKit app like Home or Hesperus to setup automation.

**Comment by pewtertankard** [comment]
Thanks for the clarification that this is an Apple issue  

Phil
