### ISSUE TITLE
10.3 Beta

### ISSUE THREAD

**Issue by samsonrosen** [KhaosT/homebridge-amazondash#13]
Hello!

Apple released a beta of 10.3 which is said to support programmable light switches.

What does that entail for the future of this plugin? Exciting stuff!

**Comment by KhaosT** [comment]
Basically iOS 10.3 allows you to setup trigger with programmable switches using Home app instead of third party app. It doesn't provide "extra" functionality.

**Comment by samsonrosen** [comment]
So is this different to using automations

**Comment by KhaosT** [comment]
No it's the same thing... you can already setup automation with programmable switches before iOS 10.3 with most of third party apps.

**Comment by samsonrosen** [comment]
But within the iOS Home app, this will be an improvement on 'Automations'.

**Comment by KhaosT** [comment]
lol not really, they picked the most awkward way to do support for programmable switch. You can try that in beta now 🙃

**Comment by mbeck94** [comment]
Using 10.3 Beta here, having issues with 2 clicks being recognized with each press

**Comment by KhaosT** [comment]
Due to the way how the plugin detect the press event on the dash button, it's not possible to detect double press with dash button.

**Comment by mbeck94** [comment]
Correct, however, its making it impossible to use single click functionality too, since each press is recognized as two

**Comment by KhaosT** [comment]
About that… Apple changed characteristic enum definition on iOS 10.3 without telling anyone in advance. Before 10.3, value 0 meaning not pressed and value 1 meaning pressed. Now they redefined 0 as single press and 1 as double press. For now if you really want to use Home app to set up programmable switches, just set double press event and ignore the single press one.

**Comment by mbeck94** [comment]
I came to that realization right after submitting that comment, to just use the double press.   Would there be a way to ignore either the arp or udp? Or is that not possible?

**Comment by KhaosT** [comment]
Ignore what?

**Comment by mbeck94** [comment]
Sorry, I'm new to this. Is there a way to have the plugin only register arp OR udp protocols? Not both?

**Comment by KhaosT** [comment]
This one only uses arp event to detect the press.

**Comment by samsonrosen** [comment]
Hi @KhaosT!

I just installed the 10.3 BETA and setup this plugin. The customisation within the Home app definitely works!

Do you have any advice for utilising the Amazon Dash as a light switch? On/Off? I can only get it to turn the lights 'on' right now.

Also, I get a fair delay for the trigger to actually happen. e.g sitting in my room in darkness looking sad whilst I await light. Is that expected behaviour?

**Comment by KhaosT** [comment]
@samsonrosen "Do you have any advice for utilising the Amazon Dash as a light switch? On/Off? I can only get it to turn the lights 'on' right now", try to setup two triggers guarded by condition of the light (**you have to use Eve or Hesperus app to create trigger with conditions**).

About the delay, yes.

**Comment by samsonrosen** [comment]
@KhaosT Thanks for your fast responses as usual!
