### ISSUE TITLE
cant install this plugin anymore

### ISSUE THREAD

**Issue by mrbeach69** [KhaosT/homebridge-amazondash#15]
In a further version there was no problem, but now I cant install and use this plugin anymore, every time I get this  message.

pi@raspberrypi:~ $ sudo npm install -g homebridge-amazondash
|
> socketwatcher@0.3.0 install /usr/local/lib/node_modules/homebridge-amazondash/node_modules/node-dash-button/node_modules/pcap/node_modules/socketwatcher
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.3.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-amazondash/node_modules/node-dash-button/node_modules/pcap/node_modules/socketwatcher/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/homebridge-amazondash/node_modules/node-dash-button/node_modules/pcap/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory '/usr/local/lib/node_modules/homebridge-amazondash/node_modules/node-dash-button/node_modules/pcap/node_modules/socketwatcher/build'

> pcap@2.0.0 install /usr/local/lib/node_modules/homebridge-amazondash/node_modules/node-dash-button/node_modules/pcap
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.3.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-amazondash/node_modules/node-dash-button/node_modules/pcap/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/homebridge-amazondash/node_modules/node-dash-button/node_modules/pcap/build'
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
../pcap_binding.cc:2:23: fatal error: pcap/pcap.h: Datei oder Verzeichnis nicht gefunden
 #include <pcap/pcap.h>
                       ^
compilation terminated.
pcap_binding.target.mk:89: recipe for target 'Release/obj.target/pcap_binding/pcap_binding.o' failed
make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/homebridge-amazondash/node_modules/node-dash-button/node_modules/pcap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.50-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-amazondash/node_modules/node-dash-button/node_modules/pcap
gyp ERR! node -v v4.3.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-amazondash"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! pcap@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pcap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pcap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

**Comment by KhaosT** [comment]
**Follow the [instruction](https://github.com/hortinstein/node-dash-button) to setup node-dash-button and figure out the MAC Address of the Dash Button.**

This is first step in the readme. You didn't install libpcap-dev.

**Comment by mrbeach69** [comment]
thank you for the quick answer, this was my issue ;-)
