### ISSUE TITLE
Amazon Dash purchase

### ISSUE THREAD

**Issue by kapps7** [KhaosT/homebridge-amazondash#16]
Hey I'm interested in investing in these and just wanted to check here before purchase. Will this plugin support any of the $4.99 amazon dash or do I need a specific one ?
Eg. there is a new one released https://www.amazon.com/dp/B01KW6YCIM

Thanks

**Comment by KhaosT** [comment]
It should work with all of them.

**Comment by kapps7** [comment]
cool thanks
