### ISSUE TITLE
Scene not triggered

### ISSUE THREAD

**Issue by benzman81** [KhaosT/homebridge-amazondash#17]
Hi,

I tried to get the plugin to work but without success. I tried Apple Home, Eve and Hesperus to configure it correctly, but my scene is never triggered. Starting in debug shows no entries when I click the button. That's why I forked the plugin to add some logging myself. Now I can see, that the button press is recognized and method dashEventWithAccessory is called, but it doesnt do anything.

Any help is appreciated.

Regards,
Markus

**Comment by KhaosT** [comment]
Are you running homebridge v0.4.19?

**Comment by benzman81** [comment]
No, still 0.4.17. Should I upgrade?

**Comment by KhaosT** [comment]
Yeah, the updated plugin requires some recent changes in homebridge (and hap-nodejs) to work properly.

**Comment by benzman81** [comment]
ok, I'll try and give feedback

**Comment by benzman81** [comment]
still no luck, the method targetChar.setValue(0); is called as my log is printed for it.

**Comment by KhaosT** [comment]
@benzman81 and if you run homebridge with debug env variable (DEBUG=* homebridge ...), does it print out anything when setValue(0) is called?

**Comment by benzman81** [comment]
wait I double check, with last version it didn't

**Comment by KhaosT** [comment]
huh ... can you make sure that homebridge is using hap-nodejs with a version that is at least v0.4.23?

**Comment by benzman81** [comment]
what is the best way to check? looking in my global node_modules folder it states 0.4.24.

**Comment by KhaosT** [comment]
``npm list -g`` and find ``hap-nodejs`` under homebridge?

**Comment by benzman81** [comment]
it states 0.4.24, too

no debug log entries after setValue(0)

**Comment by KhaosT** [comment]
Huh interesting, it should say "Sending HTTP event ..." if everything work as expected. Can you try remove the trigger on iOS device, wait a few minutes and add another trigger?

**Comment by benzman81** [comment]
Now configured it via Details screen in Apple Home. Still no luck. Other homebridge plugins trigger background events as expected.

**Comment by KhaosT** [comment]
Ah wait I know what's wrong, since you first added the button in an earlier version of homebridge, the accessory cached is missing a special flag for programmable switch characteristic. You can try to remove the accessory cache (normally under ~/.homebridge/cachedAccessories) and restart homebridge to recover. Sorry for inconveniences.

**Comment by benzman81** [comment]
Do I loose settings of all the accessories and platforms?

**Comment by KhaosT** [comment]
@benzman81 normally it shouldn't, since plugins should be able to add them back. If you are comfortable with modifying json, you can try to manually add `eventOnlyCharacteristic = true` to `ProgrammableSwitchEvent` characteristic in the accessory cache (remember to close homebridge before making changes).

**Comment by benzman81** [comment]
@KhaosT within "props" or right next to the display name?

**Comment by KhaosT** [comment]
Would you mind upload a screenshot of that section?

**Comment by KhaosT** [comment]
It's at the same level as display name and UUID.

**Comment by benzman81** [comment]
I deleted the cachedAccessories and now it works. Big thanx for your fast help!

**Comment by KhaosT** [comment]
No problem :) Good to know you got it working.
