### ISSUE TITLE
ARP expected, Dash Button only sending UDP

### ISSUE THREAD

**Issue by GatoPharaoh** [KhaosT/homebridge-amazondash#21]
Hi

I am having issues with getting my Dash Buttons to work with the plugin.
Thing is: when I use `findbutton` I can see that my Dash Buttons only use the UDP protocol - the plugin seems to only react to ARP communication as I tested it with other devices

Any tips for that?

thanks in advance

**Comment by KhaosT** [comment]
Yeah, this one currently only uses ARP so if your button only do UDP then
it won't work...

**Comment by GatoPharaoh** [comment]
#18

**Comment by GatoPharaoh** [comment]
#24 works! thanks @plasticrake
