### ISSUE TITLE
Button won't disappear after removal from config.json

### ISSUE THREAD

**Issue by GatoPharaoh** [KhaosT/homebridge-amazondash#22]
My Button won't disappear in the Home.app after removal from the config.json. Additionally, every change I make in the config.json for the amazondash plugin will result in a new Button being added to my Home.app.

The old ones just won't disappear and if I update the configuration, there will always be a new button instead of just updating the old one.

**Comment by KhaosT** [comment]
This plugin uses accessory caching, in order to properly remove the added
accessory, you can either manually delete the accessory cache file under
.homebridge or use a HomeKit app that supports homebridge plugin
configuration and remove it from there.
