### ISSUE TITLE
Button not showing up

### ISSUE THREAD

**Issue by ccaum** [KhaosT/homebridge-amazondash#4]
I've followed the instructions to get the plugin installed and configured in homebridge.  Homebridge loads the plugin, but I'm not seeing any accessories show up in HomeKit.  Am I missing a step? 
I've confirmed I have the right mac address for the button and can see a button press event when I run a script I wrote using the node-dash-button npm library.

Versions:
* Homebridge: 0.3.4
* iOS: 10 beta with Home app

config.json:
```json
{
  "bridge": {
    "name": "Homebridge",
      "username": "CC:22:3D:E3:CE:30",
      "port": 51826,
      "pin": "031-45-154"
  },

  "description": "Home Bridge",
  "platform": "AmazonDash",
  "interface": "en1",
  "buttons": [
    {
      "name": "Bounty Button",
      "mac": "AC:63:BE:B0:AC:C2"
    }
  ]
}
```

**Comment by ccaum** [comment]
I should add, I've tried running homebridge with elevated privileges.

**Comment by KhaosT** [comment]
If I remember correctly, Home app in iOS 10 doesn't support programable switches. Please try using third party HomeKit app like Eve app and see if you can find the button.

**Comment by ccaum** [comment]
Not showing up in any other HomeKit app either. I tried in iDevices, Home (the one by Matthias Hochgatterer, not the iOS 10 one), and Hesperus.

Here's my homebridge output. I don't see it creating the button device. It also says it's loading 0 platforms, which I'm guessing isn't right.

```
↪ sudo homebridge
Password:
[9/7/2016, 6:54:20 PM] Loaded plugin: homebridge-amazondash
[9/7/2016, 6:54:20 PM] Registering platform 'homebridge-amazondash.AmazonDash'
[9/7/2016, 6:54:20 PM] ---
[9/7/2016, 6:54:20 PM] Loaded plugin: homebridge-dummy
[9/7/2016, 6:54:20 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[9/7/2016, 6:54:20 PM] ---
[9/7/2016, 6:54:21 PM] Loaded plugin: homebridge-ssh
[9/7/2016, 6:54:21 PM] Registering accessory 'homebridge-ssh.SSH'
[9/7/2016, 6:54:21 PM] ---
[9/7/2016, 6:54:21 PM] Loaded config.json with 0 accessories and 0 platforms.
[9/7/2016, 6:54:21 PM] ---
Load homebridge-amazondash.AmazonDash
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[9/7/2016, 6:54:21 PM] Homebridge is running on port 51826.
```

**Comment by KhaosT** [comment]
Oops I figured it out. If you check the sample config (https://github.com/nfarina/homebridge/blob/master/config-sample.json) you can see there is a top level ''platforms'' key which contains an array of platform plugins. Please try add that to your config file and then add the plugin sample config as an element in that array. Sorry I was not at home right now, if you can't figure it out, I'll try to post a fixed config for you later today.

**Comment by ccaum** [comment]
Ah, of course. Oops. Sorry to waste your time. My Dash button is showing up in the iOS 10 Home app now.
